name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow writing to the repository

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Rust (required for cargo-binstall)
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Cache Rust dependencies and build artifacts
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Install cargo-binstall
      - name: Install cargo-binstall
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      # Install Dioxus CLI using cargo-binstall
      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli@0.6.1 --no-confirm

      # Build the Dioxus project
      - name: Build Dioxus project
        run: dx bundle

      - name: Publish
        run: |
          cp -r public/* target/dx/site/release/web/public/
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git checkout gh-pages
          rm -Rf ./docs
          mv target/dx/site/release/web/public docs
          git add .
          git commit -m "Release"
          git push origin gh-pages